added gh action

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -40,11 +40,10 @@ jobs:
   test:
     runs-on: ubuntu-latest
     needs: lint-code
-
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v3
-        
+        uses: actions/checkout@v2
+
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
@@ -63,6 +62,9 @@ jobs:
     needs: [lint-code,test]
 
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
       - name: Install Hadolint
         run: |
           sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
@@ -76,6 +78,9 @@ jobs:
     needs: analyse-Dockerfile
     
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3.0.0
   
@@ -136,26 +141,25 @@ jobs:
     needs: install-helm
     
     steps:
-
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+    
       - name: Start Minikube
-        run: minikube start --kubernetes-version=v1.20.2 --memory=4096 --cpus=2 --alsologtostderr -v=7
+        run: minikube start
       
       - name: Wait for Minikube to be Ready
         run: |
           until kubectl cluster-info; do
             sleep 5
           done
-
-      - name: Check Minikube Status
-        run: minikube status
-
-      # - name: use minikube context
-      #   run: |
-      #     kubectl config use-context minikube
+      
+      - name: use minikube context
+        run: |
+          kubectl config use-context minikube
 
       - name: Deploy with Helm
         run: |
-          helm install --debug my-release adjust_tak/helm-charts -f ./helm-charts/values.yaml \
+          helm install --debug my-release helm-charts -f ./helm-charts/values.yaml \
             --set image.registry=docker.io \
             --set image.repository=2470/home_task \
             --set image.tag=latest \
@@ -170,42 +174,31 @@ jobs:
             --set microservice.name=hello \
             --set replicaCount=3
 
-
       - name: Test Helm Deployment for /hello
         run: |
-          set -e
-          
-          # Function for retrying a command with exponential backoff
-          check_endpoint() {
-            local max_retries=5
-            local retry_interval=5
-            local attempt=1
-          
-            until curl -f -s http://127.0.0.1:5000/hello > /dev/null 2>&1; do
-              if [[ $attempt -gt $max_retries ]]; then
-                echo "Container endpoint unavailable after retries"
-                exit 2
-              fi
-              echo "Endpoint not yet available, retrying in $retry_interval seconds..."
-              sleep $retry_interval
-              retry_interval=$((retry_interval * 2))  # Exponential backoff
-              attempt=$((attempt + 1))
-            done
-          }
-          
-          # Check endpoint availability
-          check_endpoint
-          
-          # Validate response content
+          set -e  # Exit on any error
+      
+          # Retry up to 3 times with a 5-second delay
+          for i in {1..3}; do
+            curl -f http://127.0.0.1:5000/hello || true  # Silence curl output
+            if [ $? -eq 0 ]; then
+              echo "Container endpoint accessible"
+              exit 0
+            fi
+            sleep 5
+          done
+      
+          # Endpoint unavailable after retries
+          echo "Container endpoint unavailable after retries"
+          exit 2  # Specific exit code for endpoint failure
+      
+          # Additional endpoint validation
           expected_response="Hello, world!"
-          actual_response=$(curl -s http://127.0.0.1:5000/hello)
+          actual_response=$(curl -s http://127.0.0.1:5000/hello)  # Capture response
           if [[ "$actual_response" != "$expected_response" ]]; then
             echo "Unexpected response from endpoint: $actual_response"
-            exit 3
+            exit 3  # Specific exit code for incorrect response
           fi
-          
-          echo "Container endpoint accessible and response is correct"
-
       - name: Test Docker Container for /health
         run: |
             set -e  # Exit on any error
