added new config

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -120,7 +120,7 @@ jobs:
 
       - name: Install Minikube
         run: |
-          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb && chmod +x minikube && sudo mv minikube /usr/local/bin/
+          curl -LO https://github.com/kubernetes/minikube/releases/tag/v1.32.0
           sudo dpkg -i minikube_latest_amd64.deb
       
       - name: Login to Docker Hub
@@ -182,11 +182,33 @@ jobs:
       - name: Deploy with Helm to minikube
         run: |
           helm install --debug my-release helm-charts -f ./helm-charts/values.yaml 
+
+          # Wait for the pod to be ready
+          set -e
+          seconds=0
+          max_seconds=600  
+
+          while [ "$seconds" -lt "$max_seconds" ]; do
+            pod_status=$(kubectl get pods -n my-app my-release -o jsonpath='{.status.containerStatuses[0].state.waiting.reason}')
+            if [ "$pod_status" == "ImagePullBackOff" ]; then
+              echo "Image pull failed. Exiting..."
+              exit 1
+            elif [ "$pod_status" == "Running" ]; then
+              echo "Pod is running!"
+              exit 0
+            else
+              echo "Waiting for the pod to be ready. Elapsed time: $seconds seconds."
+              sleep 10
+              seconds=$((seconds+10))
+            fi
+          done
+
+          echo "Timeout: Pod did not become ready within the allotted time."
+          exit 1
       
       - name: Try the cluster !
         run: |
           kubectl get pods -A
-          kubectl get pods -n my-app
           kubectl describe pods -n my-app
       
       - name: Port-Forward Service
