added gh action

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -175,6 +175,10 @@ jobs:
       - name: use minikube context
         run: |
           kubectl config use-context minikube
+      
+      - name: Enable Minikube Dashboard
+        run: |
+          minikube dashboard
 
       - name: Deploy with Helm to minikube
         run: |
@@ -184,65 +188,30 @@ jobs:
         run: |
           kubectl get pods -n my-app
           kubectl describe pods -n my-app
-        
-      # - name: get service 
-      #   run: |
-      #     minikube service hello --url
-      #     curl $(minikube service hello --url)
-          
-
-      # - name: Test Docker Container for /hello
-      #   run: |
-      #     set -e  # Exit on any error
       
-      #     # Sleep for a while to allow the service to be fully deployed
-      #     sleep 60
+      - name: Port-Forward Service
+        run: |
+          kubectl port-forward service/hello 8080:5000 -n my-app
         
-      #     # Get Minikube IP
-      #     minikube_ip=$(minikube ip)
-        
-      #     # Get Service NodeIp and Port
-      #     node_port=$(kubectl get service hello -n my-app -o=jsonpath='{.spec.ports[0].nodePort}')
-      #     curl -f "http://${minikube_ip}:${node_port}/hello"
-        
-      #     # Retry up to 3 times with a 5-second delay
-      #     for i in {1..3}; do
-      #       curl -f "http://${cluster_ip}:${port}/hello" || true  # Silence curl output
-      #       if [ $? -eq 0 ]; then
-      #         echo "Container healthy!"
-      #         exit 0
-      #       fi
-      #       sleep 5
-      #     done
-        
-      #       echo "Container is up and running"
-      #       exit 2  # Specific exit code for container launch failure
-        
-        
-      # - name: Test Docker Container for /health
-      #   run: |
-      #     set -e  # Exit on any error
-        
-      #     sleep 20
-            
-      #     # Get Node IP and Port
-      #     node_port=$(kubectl get service hello -o=jsonpath='{.spec.ports[0].nodePort}')
-      #     curl -f "http://${minikube_ip}:${node_port}/health"
-        
-      #       # Retry up to 3 times with a 5-second delay
-      #       for i in {1..3}; do
-      #         curl -f "http://${minikube_ip}:${node_port}/health" || true  # Silence curl output
-      #         if [ $? -eq 0 ]; then
-      #           echo "Container healthy!"
+          - name: Set up cURL
+          run: sudo apt-get install -y curl
+  
+      - name: Test App with cURL
+        run: |
+          set -e  # Exit on any error
 
-      #           exit 0
-      #         fi
-
-      #         sleep 5
-
-      #       done
-        
-      #       # Health check failed after retries
-      #       echo "Container unhealthy after retries"
-      #       exit 2  # Specific exit code for health check failure
-        
+          sleep 60
+  
+          # Retry up to 3 times with a 5-second delay
+          for i in {1..3}; do
+            curl -f http://localhost:8080/hello || true  # Silence curl output
+            if [ $? -eq 0 ]; then
+              echo "App is accessible!"
+              exit 0
+            fi
+            sleep 5
+          done
+  
+          # App not accessible after retries
+          echo "App is not accessible after retries"
+          exit 2  # Specific exit code for test failure
